### ISSUE TITLE
Tests failing to find libc.so.6 and libm.so.6 on 64bit Ubuntu (SVN r147)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [davidjamesca/ctypesgen#39]
```
What steps will reproduce the problem?
1. Checkout the code
2. Go into the test directory
3. Run "./testsuite.py"

What is the expected output? What do you see instead?

I expect to see all tests pass instead I see 11 errors all like this:

======================================================================
ERROR: test_bad_args_string_not_number (__main__.MathTest)
Based on math_functions.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./testsuite.py", line 252, in setUp
    self.module, output = ctypesgentest.test(header_str, libraries=libraries, all_headers=True)
  File "/home/jlisee/projects/ctypesgen-read-only/test/ctypesgentest.py", line 52, in test
    module = __import__("temp")
  File "/home/jlisee/projects/ctypesgen-read-only/test/temp.py", line 598, in <module>
    _libs["libm.so.6"] = load_library("libm.so.6")
  File "/home/jlisee/projects/ctypesgen-read-only/test/temp.py", line 367, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libm.so.6 not found

What version of the product are you using? On what operating system?

Ubuntu 12.04 64bit, SVN r147.


Please provide any additional information below.

I have attached a patch to fix the issue.  There are still 3 tests failing with 
"AttributeError: type object 'c_uint' has no attribute '_fields_'" in the 
generated "temp.py" file.
```

Original issue reported on code.google.com by `jli...@gmail.com` on 28 Feb 2013 at 3:02

Attachments:
- [Ubuntu_64bit_fix.patch](https://storage.googleapis.com/google-code-attachments/ctypesgen/issue-39/comment-0/Ubuntu_64bit_fix.patch)

**Comment by Alan-R** [comment]
Definitely not doing that now. I run the tests on 64-bit Ubuntu all the time.
