### ISSUE TITLE
ModuleNotFoundError: No module named 'descriptions'

### ISSUE THREAD

**Issue by s97712** [davidjamesca/ctypesgen#59]
```shell
(py3) [s97712@archlinux .out]$ pip3 install ctypesgen   
Collecting ctypesgen
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b8/9d/13bcf53a190d2a5b3512d3c116920b4a2fadf007600722114b1a17602524/ctypesgen-0.r125.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-islqukxq/ctypesgen/setup.py", line 13, in <module>
        import ctypesgencore
      File "/tmp/pip-build-islqukxq/ctypesgen/ctypesgencore/__init__.py", line 60, in <module>
        import descriptions
    ModuleNotFoundError: No module named 'descriptions'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-islqukxq/ctypesgen/
(py3) [s97712@archlinux .out]$ 
```

I try to install descriptions using pip,but can't find this module.
How should i do?

**Comment by Alan-R** [comment]
This is a python3 compatibility issue. It's not compatible with python3.

**Comment by Arusekk** [comment]
Actually, this could be fixed without breaking python2 compatibility, using:
```py
from __future__ import absolute_import
```
and applicable fixes

**Comment by Alan-R** [comment]
This should be fixed now. Please reopen if the 1.0.0 version doesn't fix it.
