### ISSUE TITLE
ModuleNotFoundError: No module named 'printer_python'

### ISSUE THREAD

**Issue by scorp08** [davidjamesca/ctypesgen#64]
There is printer_python error, following  is occured in installation:
```
Traceback (most recent call last):
  File "C:\Users\lenovo\ctypesgen-master\setup.py", line 13, in <module>
    import ctypesgencore
  File "C:\Users\lenovo\ctypesgen-master\ctypesgencore\__init__.py", line 57, in <module>
    import printer_python
ModuleNotFoundError: No module named 'printer_python'
```

**Comment by olsonse** [comment]
Should use current code-base where proper relative imports are correctly utilized.
