### ISSUE TITLE
POINTER generated def makes weird crash on unrelated lib

### ISSUE THREAD

**Issue by kpoman** [davidjamesca/ctypesgen#78]
Hello,
I am loading a ctypesgenerated wrapper, which is working well.
I then started loading picamera module on the same app and saw a weird crash on the picamera.PiCamera() creation:

```
ssh://pi@192.168.1.2:22/home/pi/expybio/venvpi/bin/python -u /home/pi/pycharmdep/expybio/sensor/plugins/fingerprint/lumidigm/bug.py
mmal: mmal_vc_port_info_set: failed to set port info (3:0): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x1bffd20 (EINVAL)
Traceback (most recent call last):
  File "/home/pi/pycharmdep/expybio/sensor/plugins/fingerprint/lumidigm/bug.py", line 63, in <module>
    cam = picamera.PiCamera()
  File "/home/pi/expybio/venvpi/lib/python3.7/site-packages/picamera/camera.py", line 432, in __init__
    self._configure_camera(sensor_mode, framerate, resolution, clock_mode)
  File "/home/pi/expybio/venvpi/lib/python3.7/site-packages/picamera/camera.py", line 2079, in _configure_camera
    port.commit()
  File "/home/pi/expybio/venvpi/lib/python3.7/site-packages/picamera/mmalobj.py", line 1114, in commit
    prefix="Format couldn't be set on port %s" % self.name)
  File "/home/pi/expybio/venvpi/lib/python3.7/site-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Format couldn't be set on port vc.ril.camera:out:0: Argument is invalid

Process finished with exit code 1
```

After a lot of bughunting, I could see this def on the ctypesgenerated wrapper that was causing the crash of the later picamera object creation:

```
# C:\\tmp\\python_wrappers\\vcom_wrapper\\VCOMCore.h: 57
if hasattr(_libs['VCOMExample.dll'], 'V100_Verify'):
    V100_Verify = _libs['VCOMExample.dll'].V100_Verify
    V100_Verify.argtypes = [POINTER(c_int), POINTER(c_int), uint, POINTER(c_int), POINTER(uint)]
    V100_Verify.restype = c_int
```

In particular, the POINTER(uint) is making it crash, and just changing it to, say, POINTER(c_int) solves the problem. I then saw the POINTER definition generated on the wrapper:

```
def POINTER(obj):
    p = ctypes.POINTER(obj)

    # Convert None to a real NULL pointer to work around bugs
    # in how ctypes handles None on 64-bit platforms
    if not isinstance(p.from_param, classmethod):
        def from_param(cls, x):
            if x is None:
                return cls()
            else:
                return x
        p.from_param = classmethod(from_param)

    return p
```

Removing it, everything works, as it uses the ctypes def of POINTER. So, what can I do ? Do I just get rid of this POINTER def ? Is this a known issue ? Btw, uint is just c_uint.

All this is happening, at least, on this platform:

```

pi@IQoT-000:~/pycharmdep $ uname -a
Linux IQoT-000 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
pi@IQoT-000:~/pycharmdep $ python3 --version
Python 3.7.3
pi@IQoT-000:~/pycharmdep $ 

```

**Comment by olsonse** [comment]
Perhaps that wrapper should be regenerated.  The extra POINTER definition, as you found in your wrapper, has been removed from code generated for >Py27 back at commit 15d5b09780.  There have been a few other improvements in the generated code since then also...
